jobs:
  supported-jdk:
    continue-on-error: ${{ matrix.experimental }}
    name: ${{ matrix.title }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      if: ${{ !(matrix.experimental && github.event_name == 'pull_request') }}
      name: Checkout from Git
      uses: actions/checkout@v4
    - continue-on-error: true
      if: ${{ !(matrix.experimental && github.event_name == 'pull_request') }}
      name: Cache Maven repo
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-mvn-${{ matrix.cache-id }}-${{ hashFiles('**/pom.xml')
          }}
        path: '~/.m2/repository

          target/spotless-node-modules-prettier-format

          '
        restore-keys: '${{ runner.os }}-mvn-${{ matrix.cache-id }}

          '
    - continue-on-error: true
      if: ${{ !matrix.experimental }}
      name: Set up JDK ${{ matrix.java }} (regular)
      uses: actions/setup-java@v4
      with:
        distribution: ${{ matrix.dist }}
        java-version: ${{ matrix.java }}
    - continue-on-error: true
      if: ${{ matrix.experimental && github.event_name != 'pull_request' }}
      name: Set up JDK ${{ matrix.java }} (oracle)
      uses: oracle-actions/setup-java@v1
      with:
        release: ${{ matrix.java }}
        website: jdk.java.net
    - continue-on-error: true
      if: ${{ !(matrix.experimental && github.event_name == 'pull_request') }}
      name: Display JDK version
      run: java -version
    - continue-on-error: true
      if: ${{ !(matrix.experimental && github.event_name == 'pull_request') }}
      name: Run Maven
      run: mvn clean verify --no-transfer-progress ${{ matrix.flags }}
    strategy:
      fail-fast: false
      matrix:
        include:
        - cache-id: jdk8
          dist: temurin
          experimental: false
          flags: ''
          java: 8
          title: Supported JDK 8
        - cache-id: jdk11
          dist: temurin
          experimental: false
          flags: ''
          java: 11
          title: Supported JDK 11
        - cache-id: jdk17
          dist: temurin
          experimental: false
          flags: ''
          java: 17
          title: Supported JDK 17
        - cache-id: jdk21
          dist: temurin
          experimental: false
          flags: ''
          java: 21
          title: Supported JDK 21
        - cache-id: jdk-ea-simple
          experimental: true
          flags: -Dexperimental -DdisableStaticAnalysis
          java: ea
          title: Experimental JDK EA (simplified)
        - cache-id: jdk-ea-full
          experimental: true
          flags: -Dexperimental
          java: ea
          title: Experimental JDK EA (full)
name: CI
on:
  repository_dispatch:
    types: trigger-ga___ci.yml
