jobs:
  pitest-update-pr:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Add PITest comment
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 21
    - continue-on-error: true
      name: Download artifact
      uses: dawidd6/action-download-artifact@v3
      with:
        name: pitest
        path: target/pit-reports-ci
        workflow: ${{ github.event.workflow_run.workflow_id }}
        workflow_conclusion: success
    - continue-on-error: true
      name: update pull request
      run: mvn -DrepoToken=${{ secrets.GITHUB_TOKEN }} com.groupcdg:pitest-github-maven-plugin:0.1.0:updatePR
name: PITest comment
on:
  repository_dispatch:
    types: trigger-ga___pitest-comment.yml
