jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout from Git
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - continue-on-error: true
      name: Set up JDK
      uses: actions/setup-java@v4
      with:
        cache: maven
        distribution: temurin
        java-version: 21
    - continue-on-error: true
      name: Set release version
      run: mvn versions:set --no-transfer-progress --batch-mode -DnewVersion=${{ github.event.inputs.version
        }}
    - continue-on-error: true
      name: Update version in documentation
      run: 'sed -i "s/<version>.*<\/version>/<version>${{ github.event.inputs.version
        }}<\/version>/g" README.md

        sed -i "s/<version>.*<\/version>/<version>${{ github.event.inputs.version
        }}<\/version>/g" docs/_includes/maven

        '
    - continue-on-error: true
      name: Commit & push changes
      uses: actions-js/push@master
      with:
        github_token: ${{ secrets.JRELEASER_GITHUB_TOKEN }}
        message: Bumps version to ${{ github.event.inputs.version }}
    - continue-on-error: true
      name: Stage release
      run: mvn clean deploy --no-transfer-progress --batch-mode -DaltDeploymentRepository=local::default::file://`pwd`/target/staging-deploy
    - continue-on-error: true
      env:
        JRELEASER_GITHUB_TOKEN: ${{ secrets.JRELEASER_GITHUB_TOKEN }}
        JRELEASER_GPG_PASSPHRASE: ${{ secrets.JRELEASER_GPG_PASSPHRASE }}
        JRELEASER_GPG_PUBLIC_KEY: ${{ secrets.JRELEASER_GPG_PUBLIC_KEY }}
        JRELEASER_GPG_SECRET_KEY: ${{ secrets.JRELEASER_GPG_SECRET_KEY }}
        JRELEASER_NEXUS2_MAVEN_CENTRAL_PASSWORD: ${{ secrets.JRELEASER_NEXUS2_MAVEN_CENTRAL_PASSWORD
          }}
        JRELEASER_NEXUS2_MAVEN_CENTRAL_USERNAME: ${{ secrets.JRELEASER_NEXUS2_MAVEN_CENTRAL_USERNAME
          }}
        JRELEASER_PROJECT_VERSION: ${{ github.event.inputs.version }}
      name: Run JReleaser
      uses: jreleaser/release-action@v2
      with:
        setup-java: false
        version: 1.9.0
    - continue-on-error: true
      name: Set release version
      run: mvn versions:set --no-transfer-progress --batch-mode -DnewVersion=${{ github.event.inputs.nextVersion
        }}-SNAPSHOT
    - continue-on-error: true
      name: Commit & push changes
      uses: actions-js/push@master
      with:
        github_token: ${{ secrets.JRELEASER_GITHUB_TOKEN }}
        message: 'Prepares for next development iteration: ${{ github.event.inputs.nextVersion
          }}-SNAPSHOT'
        tags: false
    - continue-on-error: true
      name: Print diagnostic information
      run: 'echo ">>> output.properties"

        cat out/jreleaser/output.properties

        echo ""

        echo ">>> trace.log"

        cat out/jreleaser/trace.log

        '
name: Release
on:
  repository_dispatch:
    types: trigger-ga___release.yml
